### ISSUE TITLE
[Server Suggestie]: Een postnl job toevoegen voor meer afwisseling in de jobs 

### ISSUE THREAD

**Issue by gamejus** [Oostermeer/development#15]
### Contact

jeremy.#0720

### Wat is je suggestie?

Postnl pakhuis

### Wat verbeterd deze suggestie?

Het kan een realistischere baan geven als postnl werknemer

### wat hebben wij hiervoor nodig?

https://www.mediafire.com/file/bum3wxgfcug274d/PostNL.rar/file
download file

### Ga je akkoord met de richtlijnen? Indien (nee) aangedrukt, gaan we deze suggestie niet doorvoeren.

Ja

**Comment by JeremySmitss** [comment]
Ik zal dit kunnen doorvoeren, gelieve wel de volgende keer het goede format gebruiken, naast [Bug Report]: moet je de reden / issue geven, niet de [Bug Report]: veranderen met [Post NL]: 📦
