### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by MaxdeRaaf** [Oostermeer/development#34]
### Contact

YourfavoPanda#3275

### Wat gebeurde er?

/politie werkt niet om dat ie moet gereload worden is er mischien een optie om gewoon een circel temaken?
het is namelijk best vervelend als er niemand in stad is die het kan doen.

### Wat moet er normaal gesproken te gebeuren?

het politie menu teopenen

### Wat veroorzaakt de bug?

hij doet het gewoon niet

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

Hoog

### Onderhoud

Ja

**Comment by JeremySmitss** [comment]
Je bedoeld een cirkel waar je een kleedkamer in hebt?
